const Lang = {
	HOME: {
		New: 'New',
		Hot: 'Hot',
		Video: 'Video',
		Select: {
			Dance: 'Dance',
			Singing: 'Singing',
			Emotion: 'Emotion',
			Art: 'Art'
		}
	},
	FAVORITE: {
		You_May_Also_Like: 'You may also like',
		Another_Batch: 'Another batch'
	},
	MESSAGE: {
		Like: 'Like',
		Comment: 'Comment',
		System_Message: 'System  message',
		Customer_Service: 'Customer service',
		Friends: 'Friends'
	},
	USER: {
		Detail: 'Detail',
		Lists: {
			My_Video: 'My video',
			Watch_History: 'Watch history',
			Chatting_Price: 'Chatting price',
			Account: 'Account',
			Score: 'Score',
			Live_Certification: 'Live certification',
			Invite: 'Invite',
			Blacklist: 'Blacklist',
			Setting: 'Setting'
		}
	},
	PERSONAL_DETAIL: {
		Profile_Photo: 'Profile photo',
		Username: {
			Title: 'Username',
			Madal: {
				Title: 'Modify  username',
				Placeholder: 'Fill in a new username'
			}
		},
		Gender: {
			Title: 'Gender',
			Madal: {
				Male: 'Male',
				Female: 'Female'
			}
		},
		Age: {
			Title: 'Age',
			Madal: {
				Title: 'Modify birthday',
			}
		},
		Height: {
			Title: 'Height',
			Unit: 'cm',
			Madal: {
				Title: 'Modify  height',
				Placeholder: 'Fill in height (cm)'
			}
		},
		Body_Weight: {
			Title: 'Body weight',
			Unit: 'kg',
			Madal: {
				Title: 'Modify  body weight',
				Placeholder: 'Fill in body weight (kg)'
			}
		},
		Interest: {
			Title: 'Interest',
			Madal: {
				Title: 'Interest',
				Text: 'Up to 3 items can be selected',
				Lists: ['Sing', 'Digital', 'Yoga', 'Instrument', 'Movie', 'Game', 'Reading', 'Travel', 'Shopping', 'Photography', 'Cooking', 'Dancing', 'Food', 'Sports']
			}
		},
		Your_Type: {
			Title: 'Your type',
			Madal: {
				Title: 'Your type',
				Text: 'Up to 3 items can be selected',
				Lists: ['Active', 'Lovely', 'Sexy', 'Hot', 'Sunshine', 'Pretty', 'Virtuous', 'Graceful', 'Goddess', 'Charming', 'Quiet', 'Polite', 'Foxy', 'Cute']
			}
		},
		Love: {
			Title: 'Love',
			Madal: {
				Title: 'Your favorite type',
				Text: 'Up to 3 items can be selected',
				Lists: ['Sunshine', 'Warm', 'Romantic', 'Cool', 'Patience', 'Kindness', 'Handsome', 'Natural', 'Mature', 'Stable', 'Humour', 'Funny', 'Knowledgeable', 'Genius']
			}
		},
		Why_Make_Friends: {
			Title: 'Why make friends',
			Madal: {
				Title: 'Why make friends',
				Lists: ['Whatever, let me get excited', 'Long contact, no longer alone', 'For one night']
			}
		}
	},
	BAR: {
		Home: 'Home',
		Favorite: 'Favorite',
		Message: 'Message',
		Me: 'Me',
		PERSONAL_DETAIL: 'Personal details'
	},
	PUBLIC: {
		Billing: 'Gold/Min',
		Status: {
			Busy: 'Busy',
			Waiting: 'waiting'
		},
		ModalButtonOk: 'YES',
		ModalButtonCancel: 'NO',
		ConfirmButtonOk: 'Confirm',
		ConfirmButtonCancel: 'Cancel'
	}

}

export default Lang;